# モデル設定ファイル

# 再構成モデル設定
reconstruction_model:
  # モデルアーキテクチャ
  architecture: "ADMM_net"           # 使用するモデルアーキテクチャ
  dimensions: [16, 8, 8]             # 処理するパッチのサイズ
  
  # ADMM_netの設定
  stage_num: 9                       # ADMMのステージ数
  
  # UNetの設定
  unet:
    channels: [8, 16, 32, 64]        # 各層のチャンネル数
    kernel_size: 3                   # カーネルサイズ
    activation: "relu"               # 活性化関数
    use_skip_connections: true       # スキップ接続を使用するか
    
  # ガンマ値（ステップサイズ）
  gamma_init_value: 0.01             # ガンマの初期値
  gamma_trainable: true              # ガンマを学習可能にするか

# サンプリング設定
sampling_config:
  # マスク設定
  mask:
    type: "bayer_random256x256"      # マスクの種類
    dimensions: [16, 8, 8]           # マスクのサイズ
    path: "./data/mask/original"     # マスク保存ディレクトリ
    sampling_ratio: 0.5              # サンプリング率（測定数/信号次元）

  # ビット行列設定
  bit_matrix:
    temperature: 1.0                 # サンプリング温度（ソフトマスク生成用）
    binarize: true                   # ハードバイナリマスクを使用するか